# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "comana"
  s.version = "0.0.10"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["ippei94da"]
  s.date = "2014-08-28"
  s.description = "Comana, COmputation MANAger,\n    is a software to provide a framework of\n    managing scientific computing.\n    Researchers on computing have to check calculation and\n    generate new calculation and execute, repeatedly.\n    The abstract class that this gem provide would help the work.\n  "
  s.email = "ippei94da@gmail.com"
  s.executables = ["machinestatus", "scpall", "sshall"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "CHANGES",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/machinestatus",
    "bin/scpall",
    "bin/sshall",
    "example/dot.clustersetting",
    "lib/comana.rb",
    "lib/comana/clustersetting.rb",
    "lib/comana/computationmanager.rb",
    "lib/comana/hostinspector.rb",
    "lib/comana/hostinspector/pbsnodes.rb",
    "lib/comana/hostinspector/ping.rb",
    "lib/comana/hostselector.rb",
    "lib/comana/queuesubmitter.rb",
    "memo.txt",
    "test/helper.rb",
    "test/locked/input_a",
    "test/locked/input_b",
    "test/locked/lock_comana/dummy",
    "test/locked_outputted/input_a",
    "test/locked_outputted/input_b",
    "test/locked_outputted/lock_comana/dummy",
    "test/locked_outputted/output",
    "test/not_executable/dummy",
    "test/not_started/input_a",
    "test/not_started/input_b",
    "test/outputted/input_a",
    "test/outputted/input_b",
    "test/outputted/output",
    "test/pbsnodes/Br09.xml",
    "test/pbsnodes/Br10.xml",
    "test/pbsnodes/Ge00.xml",
    "test/pbsnodes/Ge08.xml",
    "test/pbsnodes/all.xml",
    "test/queuesubmitter/locked/lock_queuesubmitter/dummy",
    "test/queuesubmitter/unlocked/dummy",
    "test/test_clustersetting.rb",
    "test/test_computationmanager.rb",
    "test/test_hostinspector_pbsnodes.rb",
    "test/test_hostinspector_ping.rb",
    "test/test_hostselector.rb",
    "test/test_queuesubmitter.rb"
  ]
  s.homepage = "http://github.com/ippei94da/comana"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Manager for scientific computing"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rdoc>, ["~> 4.0.1"])
      s.add_development_dependency(%q<bundler>, ["~> 1.7.2"])
      s.add_development_dependency(%q<jeweler>, [">= 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<tefil>, [">= 0.0.3"])
    else
      s.add_dependency(%q<rdoc>, ["~> 4.0.1"])
      s.add_dependency(%q<bundler>, ["~> 1.7.2"])
      s.add_dependency(%q<jeweler>, [">= 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<tefil>, [">= 0.0.3"])
    end
  else
    s.add_dependency(%q<rdoc>, ["~> 4.0.1"])
    s.add_dependency(%q<bundler>, ["~> 1.7.2"])
    s.add_dependency(%q<jeweler>, [">= 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<tefil>, [">= 0.0.3"])
  end
end

