# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "comana"
  s.version = "0.0.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["ippei94da"]
  s.date = "2012-05-08"
  s.description = "Comana, COmputation MANAger,\n    is a software to provide a framework of\n    managing scientific computing.\n    Researchers on computing have to check calculation and\n    generate new calculation and execute, repeatedly.\n    The abstract class that this gem provide would help the work.\n  "
  s.email = "ippei94da@gmail.com"
  s.executables = ["submitqueue"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/submitqueue",
    "comana.gemspec",
    "dot.machineinfo",
    "lib/comana.rb",
    "lib/comana/computationmanager.rb",
    "lib/comana/machineinfo.rb",
    "lib/comana/queuesubmitter.rb",
    "memo.txt",
    "spec/computationmanager_spec.rb",
    "spec/locked/input_a",
    "spec/locked/input_b",
    "spec/locked/lock_comana/dummy",
    "spec/locked_outputted/input_a",
    "spec/locked_outputted/input_b",
    "spec/locked_outputted/lock_comana/dummy",
    "spec/locked_outputted/output",
    "spec/machineinfo",
    "spec/machineinfo_spec.rb",
    "spec/not_started/input_a",
    "spec/not_started/input_b",
    "spec/outputted/input_a",
    "spec/outputted/input_b",
    "spec/outputted/output",
    "spec/queuesubmitter_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/ippei94da/comana"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "Manager for scientific computing"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 2.9.0"])
      s.add_development_dependency(%q<rdoc>, [">= 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 1.1.3"])
      s.add_development_dependency(%q<jeweler>, [">= 1.8.3"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 2.9.0"])
      s.add_dependency(%q<rdoc>, [">= 3.12"])
      s.add_dependency(%q<bundler>, [">= 1.1.3"])
      s.add_dependency(%q<jeweler>, [">= 1.8.3"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 2.9.0"])
    s.add_dependency(%q<rdoc>, [">= 3.12"])
    s.add_dependency(%q<bundler>, [">= 1.1.3"])
    s.add_dependency(%q<jeweler>, [">= 1.8.3"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

